from __future__ import annotations

# French source character-length distributions (min / median / p90 / max, plus n) for every eval
# set: E2, official dev (all and each slice, `long` included), test, E1, E3 and each E2-synth
# bucket. Lengths are `len()` of the raw source string exactly as written to inputs.jsonl (the
# same quantity as the E-sets' `length` field). Percentiles use numpy's default linear
# interpolation. Read-only over data/dev, data/test and data/eval/*; writes
# reports/audit/length_distributions.{json,md}.
#
# CLI: `uv run python scripts/length_distributions.py [--out-dir reports/audit]`
import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]


def describe(lengths: Sequence[int]) -> dict[str, Any]:
    """n, min, median, p90 and max of `lengths` (p90/median by linear interpolation)."""
    if not lengths:
        raise ValueError("cannot describe an empty length list")
    arr = np.asarray(lengths, dtype=np.float64)
    return {
        "n": len(lengths),
        "min": int(arr.min()),
        "median": float(np.percentile(arr, 50)),
        "p90": float(np.percentile(arr, 90)),
        "max": int(arr.max()),
    }


def _read_rows(path: Path) -> list[dict[str, Any]]:
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def collect_groups(repo_root: Path) -> dict[str, list[int]]:
    """Group name -> French source char lengths, in the report's row order."""
    groups: dict[str, list[int]] = {}
    e2 = [len(r["source"]) for r in _read_rows(repo_root / "data" / "eval" / "e2" / "inputs.jsonl")]
    dev_rows = _read_rows(repo_root / "data" / "dev" / "inputs.jsonl")
    dev_labels = {
        r["id"]: r["slice"] for r in _read_rows(repo_root / "data" / "dev" / "labels.jsonl")
    }
    groups["e2"] = e2
    groups["dev_long_slice"] = [len(r["source"]) for r in dev_rows if dev_labels[r["id"]] == "long"]
    groups["dev_all"] = [len(r["source"]) for r in dev_rows]
    for name in sorted({dev_labels[r["id"]] for r in dev_rows} - {"long"}):
        groups[f"dev_{name}_slice"] = [
            len(r["source"]) for r in dev_rows if dev_labels[r["id"]] == name
        ]
    groups["test"] = [
        len(r["source"]) for r in _read_rows(repo_root / "data" / "test" / "inputs.jsonl")
    ]
    for name in ("e1", "e3"):
        groups[name] = [
            len(r["source"])
            for r in _read_rows(repo_root / "data" / "eval" / name / "inputs.jsonl")
        ]
    synth_rows = _read_rows(repo_root / "data" / "eval" / "e2synth" / "inputs.jsonl")
    for bucket in sorted({r["slice"] for r in synth_rows}):
        groups[bucket] = [len(r["source"]) for r in synth_rows if r["slice"] == bucket]
    return groups


def render_markdown(table: Mapping[str, Mapping[str, Any]]) -> str:
    lines = [
        "# French source length distributions (characters)",
        "",
        "`len()` of the raw French source as written to inputs.jsonl; percentiles by linear "
        "interpolation. Generated by `scripts/length_distributions.py`. E2-synth rows are "
        "synthetic (concatenations of E2 sentences).",
        "",
        "| set | n | min | median | p90 | max |",
        "|---|---|---|---|---|---|",
    ]
    for name, d in table.items():
        lines.append(
            f"| {name} | {d['n']} | {d['min']} | {d['median']:g} | {d['p90']:g} | {d['max']} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="French source char-length distributions.")
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "reports" / "audit")
    args = parser.parse_args(argv)
    table = {name: describe(v) for name, v in collect_groups(REPO_ROOT).items()}
    args.out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "unit": "characters of the raw French source (len of the inputs.jsonl `source`)",
        "percentile_method": "numpy.percentile, linear interpolation",
        "sets": table,
    }
    (args.out_dir / "length_distributions.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    (args.out_dir / "length_distributions.md").write_text(
        render_markdown(table), encoding="utf-8", newline="\n"
    )
    print(render_markdown(table))
    return 0


if __name__ == "__main__":
    sys.exit(main())
